AIzaSyBJFVNTYNGzjI4nayUMxq6DcW66eCpB1rU
######

GET https://maps.googleapis.com/maps/api/place/textsearch/json?query=coffee+shop&location=53.68204,-1.67324&key=AIzaSyBJFVNTYNGzjI4nayUMxq6DcW66eCpB1rU


######
GET http://api.getthedata.com/postcode/WF140QZ

######

GET http://http.cat/404